# Generated by Django 5.0.3 on 2024-03-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('county_fips_all', models.CharField(blank=True, max_length=255, null=True)),
                ('county_names_all', models.CharField(blank=True, max_length=255, null=True)),
                ('county_weights', models.JSONField(default=dict, help_text='Distribution of the city across counties.')),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20, unique=True)),
                ('zcta', models.BooleanField(default=False)),
                ('parent_zcta', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.CharField(max_length=50)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='location.county')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='details', serialize=False, to='location.spot')),
                ('population', models.IntegerField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('county_weights', models.JSONField(blank=True, null=True)),
                ('imprecise', models.BooleanField(default=False)),
                ('military', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='location.city'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='location.country')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='location.state'),
        ),
    ]
