# Generated by Django 5.0.3 on 2024-03-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='fips',
            field=models.CharField(max_length=5),
        ),
    ]
