# Generated by Django 5.0.3 on 2024-03-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_county_fips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
