# Generated by Django 5.0.3 on 2024-03-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_state_country_delete_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='spot',
            name='zip_code',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
