# Generated by Django 5.0.3 on 2024-03-24 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Capacity in kilograms.', validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
