# Generated by Django 5.0.3 on 2024-03-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(help_text='Weight of the cargo in kilograms.')),
                ('description', models.TextField(blank=True, help_text='Description of the cargo.', null=True)),
                ('delivery_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_deliveries', to='location.spot', verbose_name='Delivery Location')),
                ('pick_up_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_pick_ups', to='location.spot', verbose_name='Pick-up Location')),
            ],
        ),
    ]
