# Generated by Django 5.0.3 on 2024-03-24 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='weight',
            field=models.PositiveIntegerField(help_text='Weight of the cargo in kilograms.', validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
