def get_cargo_names() -> list:
    cargo_name_list = [
        "Electronics",
        "Furniture",
        "Clothing",
        "Auto parts",
        "Medical supplies",
        "Construction materials",
        "Food products",
        "Office supplies",
        "Computer equipment",
        "Household appliances",
        "Toys",
        "Sports equipment",
        "Books",
        "Musical instruments",
        "Alcoholic beverages",
        "Cosmetics",
        "Agricultural products",
        "Pet supplies",
        "Footwear",
        "Jewelry",
        "Art supplies",
        "Gardening tools",
        "Photography equipment",
        "Video games",
        "Home decor",
        "Bicycles",
        "Fitness equipment",
        "Watches",
        "Sunglasses",
        "Ceramics",
        "Leather goods",
        "Stationery",
        "Textiles",
        "Paper products",
        "Plastics",
        "Chemicals",
        "Metals",
        "Wood products",
        "Machinery",
        "Industrial tools",
        "Electrical components",
        "Lighting fixtures",
        "Sanitary products",
        "Tiles and flooring",
        "Wallpapers",
        "Carpets",
        "Window treatments",
        "Outdoor furniture",
        "Grains and seeds",
        "Beverages",
        "Confectionery",
        "Pharmaceuticals",
        "Biotech products",
        "Automobiles",
        "Motorcycles",
        "Boats",
        "Aircraft parts",
        "Railroad equipment",
        "Mining equipment",
        "Oil and gas equipment",
        "Renewable energy equipment",
        "Defense and military equipment",
        "Spacecraft components",
        "Scientific research equipment",
        "Architectural models",
        "Exhibition materials",
        "Event supplies",
        "Emergency relief supplies",
        "Postal packages",
        "Courier parcels",
        "E-commerce goods",
        "Custom fabricated items",
        "Prototype products",
        "Bulk commodities",
        "Recyclable materials",
        "Waste materials",
        "Artwork",
        "Antiques",
        "Collectibles",
        "Rare items",
        "Frozen foods",
        "Seafood",
        "Dairy products",
        "Meat products",
        "Fruits and vegetables",
        "Grains and cereals",
        "Coffee and tea",
        "Spices and herbs",
        "Organic products",
        "Vegan products",
        "Gluten-free products",
        "Energy drinks",
        "Mineral water",
        "Wine and spirits",
        "Craft beer",
        "Baby products",
        "Pet food",
        "Aquarium supplies",
        "Camping gear",
        "Travel accessories",
        "Swimwear",
        "Winter sports gear",
        "Surfing equipment",
        "Climbing gear",
        "Hunting equipment",
        "Fishing gear",
        "Golf equipment",
        "Team sports equipment",
        "Athletic wear",
        "Yoga mats and accessories",
        "Skincare products",
        "Haircare products",
        "Makeup",
        "Perfumes and fragrances",
        "Bath and body products",
        "Nail care products",
        "Beauty tools and accessories",
        "Home cleaning supplies",
        "Laundry products",
        "Eco-friendly cleaning products",
        "Air fresheners",
        "Paper towels and tissues",
        "Disposable tableware",
        "Party decorations",
        "Gift wrapping supplies",
        "Greeting cards",
        "Board games and puzzles",
        "Educational toys",
        "Electronic toys",
        "Dolls and action figures",
        "Model kits",
        "Remote control vehicles",
        "Outdoor play equipment",
        "Children's books",
        "Comics and graphic novels",
        "Magazines and journals",
        "Academic textbooks",
        "Self-help books",
        "Cookbooks",
        "Biographies and memoirs",
        "Science fiction and fantasy novels",
        "Mystery and thriller novels",
        "Romance novels",
        "Historical fiction",
        "Poetry and literary collections",
        "Art and photography books",
        "Travel guides",
        "Language learning materials",
        "Sheet music and songbooks",
        "Recording equipment",
        "DJ equipment",
        "Musical accessories",
        "Sound systems",
        "Headphones and earbuds",
        "Smartphones and accessories",
        "Tablets and e-readers",
        "Laptops and desktop computers",
        "Computer components and peripherals",
        "Networking devices",
        "Smart home devices",
        "Wearable technology",
        "Video cameras and accessories",
        "Projectors and screens",
        "Streaming devices",
        "Virtual reality equipment",
        "Console and PC video games",
        "Gaming accessories",
        "Collectible card games",
        "Role-playing games",
        "Fabric and sewing supplies",
        "Knitting and crochet supplies",
        "Painting and drawing supplies",
        "Craft kits",
        "Jewelry making supplies",
        "Candle and soap making kits",
        "Scrapbooking materials",
        "Party and event supplies",
        "Wedding decorations",
        "Costumes and accessories",
        "Fireworks",
        "Religious and ceremonial items",
        "Flags and banners",
        "Signage and display materials",
        "Industrial fasteners",
        "Welding supplies",
        "Plumbing supplies",
        "Electrical supplies",
        "Hand tools",
        "Power tools",
        "Tool storage",
        "Safety equipment",
        "Workwear",
        "Laboratory supplies",
        "Medical devices",
        "Dental supplies",
        "Veterinary supplies",
        "Rehabilitation equipment",
        "Diagnostic tests",
        "Surgical instruments",
        "Hospital furniture",
        "Disposables and consumables",
        "Cleaning and sterilization supplies",
        "Educational supplies",
        "Office furniture",
        "Printing supplies",
        "Presentation equipment",
        "Mailing and shipping supplies",
        "Storage solutions",
        "Security systems",
        "Banking and financial supplies",
        "Legal document supplies",
        "Real estate marketing materials",
        "Agricultural machinery",
        "Farm supplies",
        "Livestock feed",
        "Horticultural supplies",
        "Forestry equipment",
        "Fishing and aquaculture supplies",
        "Mining and quarrying equipment",
        "Oilfield supplies",
        "Renewable energy systems",
        "Environmental monitoring equipment",
        "Waste management supplies",
        "Water treatment supplies",
        "Construction vehicles",
        "Heavy machinery",
        "Building supplies",
        "Flooring and tiles",
        "Windows and doors",
        "Roofing materials",
        "Insulation and sealants",
        "Paints and coatings",
        "Handrails and balustrades",
        "Bathroom fixtures",
        "Kitchen appliances",
        "Historical artifacts"
    ]

    return cargo_name_list
